name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: 14 5 * * *

jobs:
  run_bing2weibo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: run bing2weibo.py
      env:
        WEIBO_TOKEN: ${{secrets.WEIBO_TOKEN}}
      run: |
        git config --global user.email super_gxq@qq.com
        git config --global user.name xianqiangjun
        git init
        python b2v_actions.py
    
    - name: commit
      run: |
        git add .
        git commit -m "update log"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
